"""Id;" \
"en_curid;" \
"Name;" \
"NameURL;" \
"Link;" \
"birthcity;" \
"countryName;" \
"countryCode_alpha2;" \
"countryCode_alpha3;" \
"longitude;" \
"latitude;" \
"continentName;" \
"birthyear;" \
"deathyear;" \
"agespan;" \
"gender;" \
"occupation;" \
"industry;" \
"domain;" \
"domain2;" \
"L_star;" \
"numLangs;" \
"averageViews;" \
"totalPageViews;" \
"stdDevPageViews;" \
"pageViewsEnglish;" \
"pageViewsNonEnglish;" \
"HPI;" \
"timeInterval;" \
"pageRank;" \
"eccentricity;" \
"closenessCentrality;" \
"harmonicClosenessCentrality;" \
"betweenessCentrality;" \
"authority;" \
"hub;" \
"indegree;" \
"outdegree;" \
"degree;" \
"clustering;" \
"eigenCentrality;" \
"BCI"""